/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.ignite;

import java.io.*;

/**
 * Students definition.
 *
 * Code generated by Apache Ignite Schema Import utility: 11/23/2015.
 */
public class Students implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for studentid. */
    private Integer studentid;

    /** Value for lastname. */
    private String lastname;

    /** Value for firstname. */
    private String firstname;

    /** Value for gpa. */
    private Float gpa;

    /** Value for scheduleid. */
    private Integer scheduleid;

    /**
     * Gets studentid.
     *
     * @return Value for studentid.
     */
    public Integer getStudentid() {
        return studentid;
    }

    /**
     * Sets studentid.
     *
     * @param studentid New value for studentid.
     */
    public void setStudentid(Integer studentid) {
        this.studentid = studentid;
    }

    /**
     * Gets lastname.
     *
     * @return Value for lastname.
     */
    public String getLastname() {
        return lastname;
    }

    /**
     * Sets lastname.
     *
     * @param lastname New value for lastname.
     */
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    /**
     * Gets firstname.
     *
     * @return Value for firstname.
     */
    public String getFirstname() {
        return firstname;
    }

    /**
     * Sets firstname.
     *
     * @param firstname New value for firstname.
     */
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    /**
     * Gets gpa.
     *
     * @return Value for gpa.
     */
    public Float getGpa() {
        return gpa;
    }

    /**
     * Sets gpa.
     *
     * @param gpa New value for gpa.
     */
    public void setGpa(Float gpa) {
        this.gpa = gpa;
    }

    /**
     * Gets scheduleid.
     *
     * @return Value for scheduleid.
     */
    public Integer getScheduleid() {
        return scheduleid;
    }

    /**
     * Sets scheduleid.
     *
     * @param scheduleid New value for scheduleid.
     */
    public void setScheduleid(Integer scheduleid) {
        this.scheduleid = scheduleid;
    }

    /** {@inheritDoc} */
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;

        if (!(o instanceof Students))
            return false;

        Students that = (Students)o;

        if (studentid != null ? !studentid.equals(that.studentid) : that.studentid != null)
            return false;

        if (lastname != null ? !lastname.equals(that.lastname) : that.lastname != null)
            return false;

        if (firstname != null ? !firstname.equals(that.firstname) : that.firstname != null)
            return false;

        if (gpa != null ? !gpa.equals(that.gpa) : that.gpa != null)
            return false;

        if (scheduleid != null ? !scheduleid.equals(that.scheduleid) : that.scheduleid != null)
            return false;

        return true;
    }

    /** {@inheritDoc} */
    @Override public int hashCode() {
        int res = studentid != null ? studentid.hashCode() : 0;

        res = 31 * res + (lastname != null ? lastname.hashCode() : 0);

        res = 31 * res + (firstname != null ? firstname.hashCode() : 0);

        res = 31 * res + (gpa != null ? gpa.hashCode() : 0);

        res = 31 * res + (scheduleid != null ? scheduleid.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} */
    @Override public String toString() {
        return "Students [studentid=" + studentid +
            ", lastname=" + lastname +
            ", firstname=" + firstname +
            ", gpa=" + gpa +
            ", scheduleid=" + scheduleid +
            "]";
    }
}

