/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.ignite;

import java.io.*;

/**
 * StudentsKey definition.
 *
 * Code generated by Apache Ignite Schema Import utility: 11/23/2015.
 */
public class StudentsKey implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for studentid. */
    private Integer studentid;

    /**
     * Gets studentid.
     *
     * @return Value for studentid.
     */
    public Integer getStudentid() {
        return studentid;
    }

    /**
     * Sets studentid.
     *
     * @param studentid New value for studentid.
     */
    public void setStudentid(Integer studentid) {
        this.studentid = studentid;
    }

    /** {@inheritDoc} */
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;

        if (!(o instanceof StudentsKey))
            return false;

        StudentsKey that = (StudentsKey)o;

        if (studentid != null ? !studentid.equals(that.studentid) : that.studentid != null)
            return false;

        return true;
    }

    /** {@inheritDoc} */
    @Override public int hashCode() {
        int res = studentid != null ? studentid.hashCode() : 0;

        return res;
    }

    /** {@inheritDoc} */
    @Override public String toString() {
        return "StudentsKey [studentid=" + studentid +
            "]";
    }
}

